"""esquema inicial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-10 07:48:47.362595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de la revisión, usados por Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_notificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origen_servicio', sa.String(length=50), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('procesado', sa.Boolean(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('procesado_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_notificacion_procesado'), 'eventos_notificacion', ['procesado'], unique=False)
    op.create_index(op.f('ix_eventos_notificacion_tipo_evento'), 'eventos_notificacion', ['tipo_evento'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('cambio_estado_postulacion', 'postulacion_recibida', 'postulacion_aceptada', 'postulacion_rechazada', 'postulacion_en_revision', 'postulacion_entrevista', 'practica_iniciada', 'practica_finalizada', 'practica_suspendida', 'vencimiento_proximo', 'evaluacion_pendiente', 'informe_pendiente', 'informe_aprobado', 'nueva_vacante_matching', 'vacante_cerrada', 'bienvenida', 'sistema', name='tipo_notificacion_enum'), nullable=False),
    sa.Column('canal', sa.Enum('email', 'push', 'in_app', name='canal_enum'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('leida_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado_envio', sa.Enum('pendiente', 'enviado', 'fallido', 'omitido', name='estado_envio_enum'), nullable=False),
    sa.Column('error_envio', sa.Text(), nullable=True),
    sa.Column('datos_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_created_at'), 'notificaciones', ['created_at'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_created_at'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_eventos_notificacion_tipo_evento'), table_name='eventos_notificacion')
    op.drop_index(op.f('ix_eventos_notificacion_procesado'), table_name='eventos_notificacion')
    op.drop_table('eventos_notificacion')
    # ### end Alembic commands ###
